### ISSUE TITLE
Auto Height Center-Border Layout Instead of Autoscroll=true

### ISSUE THREAD

**Issue by shukrimb** [tony1223/zkfiddle#166]
Hi Tony,

Just to inform u that I'm really new in ZK framework. Actually, I've one(1) problem on how to set Center Frane at Border Layout to follow the content information where if the page height is less than 100%, it will display full of the page but if more than 100% height, so browser scrollbar will appear. currently, when I set autoscroll=true, it just enable a scrollbar at Center itself, but my requirement is, how to make the Center follow the size of the page.

Thanking u in advanced for your help.

Regards
Shukri

**Comment by tony1223** [comment]
Please feel free to post this usage question to ZK forum.
http://www.zkoss.org/forum/listDiscussion/14 

This issue tracker is only for ZK fiddle project .
