### ISSUE TITLE
change the tab implementation to use image for different type

### ISSUE THREAD

**Issue by tony1223** [tony1223/zkfiddle#77]
A suggestion from @simonpai , and discussed with @flyworld.

**Comment by ryanhanwu** [comment]
i prefer have file type icon at the front of tab label (easy and pretty <3 )

**Comment by tony1223** [comment]
Ok , that need any customization from me or not ?

**Comment by tony1223** [comment]
As discussed with @flyworld  , we are going to use image handle this.

Not sure if we have some restriction for placing a image in a tab ,
@flyworld will try to handle image first and push ui, if there any restriction for tab , I will try to customize it later.

**Comment by tony1223** [comment]
Add a basic implementation , might need fine tune the image , close it first.

**Comment by ryanhanwu** [comment]
nice
