### ISSUE TITLE
using JKMount for apache instead of mod_proxy

### ISSUE THREAD

**Issue by tony1223** [tony1223/zkfiddle#97]
production issue.

Better performance , and less information lost.

**Comment by zanyking** [comment]
Jetty also support AJP, so we can use mod_jk instead.
But I think you already know that.

**Comment by tony1223** [comment]
In local dev , we didn't need mod_jk,
this one is production issue.

Currently we use Apache2 to handle all request to zkfiddle.org then proxy to the Tomcat.

**Comment by tony1223** [comment]
Done.
